### ISSUE TITLE
License

### ISSUE THREAD

**Issue by luckylooke** [coverslide/node-alea#2]
Johannes Baagøe doesnt seems to have working web.. is there a some license restrictions using the code?

**Comment by dabbr** [comment]
// http://baagoe.org/en/wiki/Better_random_numbers_for_javascript
// Copyright (C) 2010 by Johannes Baagøe <baagoe@baagoe.org>
// MIT License - http://en.wikipedia.org/wiki/MIT_License
// Modified
https://github.com/tapio/infiniverse/blob/master/js/alea.js

**Comment by luckylooke** [comment]
Thanks :)
